<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyTitle>AsmSpy.CommandLine</AssemblyTitle>
    <AssemblyCompany>Suteki Ltd</AssemblyCompany>
    <AssemblyProduct>AsmSpy.CommandLine</AssemblyProduct>
    <AssemblyCopyright>Copyright Suteki Ltd</AssemblyCopyright>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
    <FileVersion>1.2.0.0</FileVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ILMerge" Version="3.0.29" />
    <PackageReference Include="Microsoft.Extensions.CommandLineUtils" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AsmSpy.Core\AsmSpy.Core.csproj" />
  </ItemGroup>



  <!-- ILMerge Integration -->
  <PropertyGroup>
    <NuGetPackagesPath>$(SolutionDir)\packages</NuGetPackagesPath>
  </PropertyGroup>

  <Target Name="MergeExecutable" AfterTargets="Build" Inputs="$(OutputPath)\Microsoft.Extensions.CommandLineUtils.dll;$(OutputPath)\$(AssemblyName).exe" Outputs="$(OutputPath)Merged\AsmSpy.exe" Condition=" '$(OS)' == 'Windows_NT'">
    <PropertyGroup>
      <NuGetRoot>$(NuGetPackagesPath)</NuGetRoot>
      <ILMergeExe>$(NuGetRoot)\ILMerge.3.0.29\tools\net452\ILMerge.exe</ILMergeExe>
      <ILMergeInternalizeIgnoreFile>$(MSBuildProjectDirectory)\ilmerge.internalize.ignore.txt</ILMergeInternalizeIgnoreFile>
      <ILMergeOutputFile>AsmSpy.exe</ILMergeOutputFile>
      <ILMergeOutputFilePath>$(OutputPath)$(ILMergeOutputFile)</ILMergeOutputFilePath>
      <FrameworkPath>$(ProgramFiles)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2</FrameworkPath>
      <FrameworkPath Condition="'$(MSBuildProgramFiles32)' != ''">$(MSBuildProgramFiles32)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2</FrameworkPath>
      <ILMergeCommandArgs>/targetplatform:"v4, $(FrameworkPath)" /internalize:"$(ILMergeInternalizeIgnoreFile)" /target:exe /out:"Merged\$(ILMergeOutputFile)" /log:"Merged\ilmerge.msbuild.log" /allowDup AsmSpy.CommandLine.exe AsmSpy.Core.dll Microsoft.Extensions.CommandLineUtils.dll</ILMergeCommandArgs>
    </PropertyGroup>
    <ItemGroup>
      <ILMergeItems Include="$(OutputPath)\*.dll;$(OutputPath)\*.exe" />
    </ItemGroup>
    <MakeDir Directories="$(OutputPath)Merged" Condition="!Exists('$(OutputPath)Merged')" />
    <Delete Files="$(ILMergeOutputFilePath)" Condition="Exists($(ILMergeOutputFilePath))" />
    <Error Condition="!Exists('$(FrameworkPath)')" Text="Could not find 4.0 reference assemblies in $(FrameworkPath)" />
    <Exec Command="&quot;$(ILMergeExe)&quot; $(ILMergeCommandArgs)" WorkingDirectory="$(OutputPath)" />
    <Delete Files="$(OutputPath)AsmSpy.exe" Condition="Exists('$(OutputPath)AsmSpy.exe')" />
    <Delete Files="$(OutputPath)AsmSpy.pdb" Condition="Exists('$(OutputPath)AsmSpy.pdb')" />
    <Delete Files="$(OutputPath)ilmerge.msbuild.log" Condition="Exists('$(OutputPath)ilmerge.msbuild.log')" />
    <Move SourceFiles="$(OutputPath)Merged\AsmSpy.exe" DestinationFolder="$(OutputPath)" Condition="Exists('$(OutputPath)Merged\AsmSpy.exe')" />
    <Move SourceFiles="$(OutputPath)Merged\AsmSpy.pdb" DestinationFolder="$(OutputPath)" Condition="Exists('$(OutputPath)Merged\AsmSpy.pdb')" />
    <Move SourceFiles="$(OutputPath)Merged\ilmerge.msbuild.log" DestinationFolder="$(OutputPath)" Condition="Exists('$(OutputPath)Merged\ilmerge.msbuild.log')" />
    <RemoveDir Directories="$(OutputPath)Merged" Condition="Exists('$(OutputPath)Merged')" />
  </Target>

</Project>