<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyTitle>AsmSpy.Core</AssemblyTitle>
    <AssemblyCompany>Suteki Ltd</AssemblyCompany>
    <AssemblyProduct>AsmSpy.Core</AssemblyProduct>
    <AssemblyCopyright>Copyright Suteki Ltd</AssemblyCopyright>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
    <FileVersion>1.2.0.0</FileVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>CODE_ANALYSIS;DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="UnitTests.cs" />
  </ItemGroup>

</Project>